// Bundles the Action to a single ESM file (dist/index.js) for `runs: using: node20`.
//
// The @actions toolchain (core@3 / github@9 / artifact@6) and its octokit@7 deps are
// ESM-only, so the Action is ESM (package.json "type": "module"); ncc (CJS-only output)
// can't bundle that, esbuild can. Two ESM-for-node necessities:
//   • banner: re-create `require` / `__dirname` / `__filename` — some bundled CJS deps
//     do a runtime `require('net')`/etc., which an ESM bundle otherwise lacks.
//   • the dist/licenses.txt compliance artifact (the bundled deps' license texts) is
//     regenerated here from the production dependency tree — esbuild's --legal-comments
//     only extracts inline banners, not full texts, so we walk node_modules ourselves.
// ── ACCEPTED ADVISORY, argued rather than suppressed (re-read this before re-reporting it) ──
//
// `npm audit` reports esbuild <=0.24.2 MODERATE — GHSA-67mh-4wv8-2f99, "esbuild enables any
// website to send any requests to the development server and read the response". It is left
// UNFIXED, deliberately, and the argument is about REACHABILITY rather than severity:
//
//   • the advisory is entirely about esbuild's DEV SERVER (`serve()` / `--serve`). This file
//     imports exactly one esbuild symbol, `build`, calls it once and exits. `serve` is never
//     imported, so the vulnerable surface cannot be instantiated.
//   • esbuild is a devDependency ONLY — `package.json` has it under `devDependencies` and NOT
//     under `dependencies`, which is the structural fact; it builds `dist/index.js` and never
//     runs on a consumer's runner. (Do not try to confirm that by grepping the artifacts: the
//     `esbuild` string DOES occur in both, as this generator's header line in
//     `dist/licenses.txt` and as undici's `esbuildDetection` feature probe in `dist/index.js`.
//     Neither is an esbuild licence block or an esbuild import — a grep here yields false
//     positives, which is why the dependency-section fact is the one cited.)
//   • the fix is esbuild 0.28.2, a SEMVER-MAJOR bump of the tool that produces the shipped
//     bundle. Taking a major on the bundler to close a dev-server issue we do not have would
//     move the artifact every consumer runs, to fix nothing reachable.
//
// This is an exception with a reason, not a suppression: no `--force`, no audit-level flag, no
// ignore file. If the build ever gains `serve()`, or esbuild becomes a runtime dependency, this
// paragraph is void and the bump is owed. Re-verified 2026-08-10; the other three advisories in
// that audit (adm-zip HIGH, brace-expansion HIGH, undici MODERATE) were all TAKEN.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const banner = [
    "import { createRequire as __cr } from 'node:module';",
    "import { fileURLToPath as __furl } from 'node:url';",
    "import { dirname as __dir } from 'node:path';",
    'const require = __cr(import.meta.url);',
    'const __filename = __furl(import.meta.url);',
    'const __dirname = __dir(__filename);',
].join('\n');

const result = await build({
    entryPoints: ['src/main.ts'],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    outfile: 'dist/index.js',
    banner: { js: banner },
    legalComments: 'none',
    metafile: true,
});

// dist/licenses.txt — the license text of every package ACTUALLY bundled into
// dist/index.js, so the proprietary distribution carries the third-party
// attributions (README § License). Derived from esbuild's metafile (the precise
// set of inputs), so it can't drift from what shipped — no dep-tree guessing.
function packageRoot(inputPath) {
    // "node_modules/@scope/name/lib/x.js" → "node_modules/@scope/name"; nested node_modules → the LAST one.
    const idx = inputPath.lastIndexOf('node_modules/');
    if (idx === -1) return null;
    const rest = inputPath.slice(idx + 'node_modules/'.length).split('/');
    const name = rest[0].startsWith('@') ? `${rest[0]}/${rest[1]}` : rest[0];
    return { name, dir: inputPath.slice(0, idx) + 'node_modules/' + name };
}
function licenseText(dir) {
    let entries;
    try {
        entries = readdirSync(dir);
    } catch {
        return null;
    }
    for (const f of entries.sort()) {
        if (/^(LICENSE|LICENCE|COPYING|NOTICE)(\..*)?$/i.test(f)) {
            const p = join(dir, f);
            if (statSync(p).isFile()) return readFileSync(p, 'utf8').trimEnd();
        }
    }
    return null;
}
const pkgs = new Map(); // name → dir (dedup; first node_modules path wins)
for (const input of Object.keys(result.metafile.inputs)) {
    const root = packageRoot(input);
    if (root && !pkgs.has(root.name)) pkgs.set(root.name, root.dir);
}
const blocks = [
    'Sift Action — license texts of the third-party packages bundled into dist/index.js.',
    'Generated by esbuild.config.mjs from the build metafile (the exact bundled set).',
    '',
];
for (const name of [...pkgs.keys()].sort()) {
    const dir = pkgs.get(name);
    let version = 'unknown';
    try {
        version = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')).version ?? 'unknown';
    } catch {
        /* keep unknown */
    }
    blocks.push('='.repeat(78), `${name}@${version}`, '='.repeat(78));
    blocks.push(licenseText(dir) ?? '(no LICENSE/COPYING/NOTICE file shipped in this package)', '');
}
writeFileSync('dist/licenses.txt', blocks.join('\n') + '\n');
console.log(`dist/index.js + dist/licenses.txt written (${pkgs.size} bundled packages)`);
