// Bundles the Action to a single ESM file (dist/index.js) for `runs: using: node20`.
//
// The @actions toolchain (core@3 / github@9 / artifact@6) and its octokit@7 deps are
// ESM-only, so the Action is ESM (package.json "type": "module"); ncc (CJS-only output)
// can't bundle that, esbuild can. Two ESM-for-node necessities:
//   • banner: re-create `require` / `__dirname` / `__filename` — some bundled CJS deps
//     do a runtime `require('net')`/etc., which an ESM bundle otherwise lacks.
//   • the dist/licenses.txt compliance artifact (the bundled deps' license texts) is
//     regenerated here from the production dependency tree — esbuild's --legal-comments
//     only extracts inline banners, not full texts, so we walk node_modules ourselves.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const banner = [
    "import { createRequire as __cr } from 'node:module';",
    "import { fileURLToPath as __furl } from 'node:url';",
    "import { dirname as __dir } from 'node:path';",
    'const require = __cr(import.meta.url);',
    'const __filename = __furl(import.meta.url);',
    'const __dirname = __dir(__filename);',
].join('\n');

const result = await build({
    entryPoints: ['src/main.ts'],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node20',
    outfile: 'dist/index.js',
    banner: { js: banner },
    legalComments: 'none',
    metafile: true,
});

// dist/licenses.txt — the license text of every package ACTUALLY bundled into
// dist/index.js, so the proprietary distribution carries the third-party
// attributions (README § License). Derived from esbuild's metafile (the precise
// set of inputs), so it can't drift from what shipped — no dep-tree guessing.
function packageRoot(inputPath) {
    // "node_modules/@scope/name/lib/x.js" → "node_modules/@scope/name"; nested node_modules → the LAST one.
    const idx = inputPath.lastIndexOf('node_modules/');
    if (idx === -1) return null;
    const rest = inputPath.slice(idx + 'node_modules/'.length).split('/');
    const name = rest[0].startsWith('@') ? `${rest[0]}/${rest[1]}` : rest[0];
    return { name, dir: inputPath.slice(0, idx) + 'node_modules/' + name };
}
function licenseText(dir) {
    let entries;
    try {
        entries = readdirSync(dir);
    } catch {
        return null;
    }
    for (const f of entries.sort()) {
        if (/^(LICENSE|LICENCE|COPYING|NOTICE)(\..*)?$/i.test(f)) {
            const p = join(dir, f);
            if (statSync(p).isFile()) return readFileSync(p, 'utf8').trimEnd();
        }
    }
    return null;
}
const pkgs = new Map(); // name → dir (dedup; first node_modules path wins)
for (const input of Object.keys(result.metafile.inputs)) {
    const root = packageRoot(input);
    if (root && !pkgs.has(root.name)) pkgs.set(root.name, root.dir);
}
const blocks = [
    'Sift Action — license texts of the third-party packages bundled into dist/index.js.',
    'Generated by esbuild.config.mjs from the build metafile (the exact bundled set).',
    '',
];
for (const name of [...pkgs.keys()].sort()) {
    const dir = pkgs.get(name);
    let version = 'unknown';
    try {
        version = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8')).version ?? 'unknown';
    } catch {
        /* keep unknown */
    }
    blocks.push('='.repeat(78), `${name}@${version}`, '='.repeat(78));
    blocks.push(licenseText(dir) ?? '(no LICENSE/COPYING/NOTICE file shipped in this package)', '');
}
writeFileSync('dist/licenses.txt', blocks.join('\n') + '\n');
console.log(`dist/index.js + dist/licenses.txt written (${pkgs.size} bundled packages)`);
